name: vcpkg (manifest) install

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap vcpkg
        shell: pwsh
        run: |
          cd "$env:GITHUB_WORKSPACE\vcpkg"
          .\bootstrap-vcpkg.bat

      - name: Install dependencies (manifest)
        shell: pwsh
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
          VCPKG_FEATURE_FLAGS: manifests
        run: |
          cd "$env:GITHUB_WORKSPACE"
          & "$env:VCPKG_ROOT\vcpkg.exe" install --triplet $env:VCPKG_DEFAULT_TRIPLET --clean-after-build
